//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 03:35:44 ���� CST 
//


package com.richitec.donkey.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}primitiveType">
 *       &lt;sequence>
 *         &lt;element name="pattern" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *                 &lt;attribute name="digits" use="required" type="{}basicDigits.datatype" />
 *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" fixed="moml+digits" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="noinput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nomatch" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dtmfexit" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="cleardb" type="{}boolean.datatype" default="true" />
 *       &lt;attribute name="fdt" type="{}posDuration.datatype" default="0s" />
 *       &lt;attribute name="idt" type="{}posDuration.datatype" default="4s" />
 *       &lt;attribute name="edt" type="{}posDuration.datatype" default="4s" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pattern",
    "noinput",
    "nomatch",
    "dtmfexit"
})
public class Dtmf
    extends PrimitiveType
{

    @XmlElement(required = true)
    protected List<Dtmf.Pattern> pattern;
    protected Dtmf.Noinput noinput;
    protected Dtmf.Nomatch nomatch;
    protected Dtmf.Dtmfexit dtmfexit;
    @XmlAttribute
    protected BooleanDatatype cleardb;
    @XmlAttribute
    protected String fdt;
    @XmlAttribute
    protected String idt;
    @XmlAttribute
    protected String edt;

    /**
     * Gets the value of the pattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dtmf.Pattern }
     * 
     * 
     */
    public List<Dtmf.Pattern> getPattern() {
        if (pattern == null) {
            pattern = new ArrayList<Dtmf.Pattern>();
        }
        return this.pattern;
    }

    /**
     * Gets the value of the noinput property.
     * 
     * @return
     *     possible object is
     *     {@link Dtmf.Noinput }
     *     
     */
    public Dtmf.Noinput getNoinput() {
        return noinput;
    }

    /**
     * Sets the value of the noinput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dtmf.Noinput }
     *     
     */
    public void setNoinput(Dtmf.Noinput value) {
        this.noinput = value;
    }

    /**
     * Gets the value of the nomatch property.
     * 
     * @return
     *     possible object is
     *     {@link Dtmf.Nomatch }
     *     
     */
    public Dtmf.Nomatch getNomatch() {
        return nomatch;
    }

    /**
     * Sets the value of the nomatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dtmf.Nomatch }
     *     
     */
    public void setNomatch(Dtmf.Nomatch value) {
        this.nomatch = value;
    }

    /**
     * Gets the value of the dtmfexit property.
     * 
     * @return
     *     possible object is
     *     {@link Dtmf.Dtmfexit }
     *     
     */
    public Dtmf.Dtmfexit getDtmfexit() {
        return dtmfexit;
    }

    /**
     * Sets the value of the dtmfexit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dtmf.Dtmfexit }
     *     
     */
    public void setDtmfexit(Dtmf.Dtmfexit value) {
        this.dtmfexit = value;
    }

    /**
     * Gets the value of the cleardb property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getCleardb() {
        if (cleardb == null) {
            return BooleanDatatype.TRUE;
        } else {
            return cleardb;
        }
    }

    /**
     * Sets the value of the cleardb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setCleardb(BooleanDatatype value) {
        this.cleardb = value;
    }

    /**
     * Gets the value of the fdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFdt() {
        if (fdt == null) {
            return "0s";
        } else {
            return fdt;
        }
    }

    /**
     * Sets the value of the fdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFdt(String value) {
        this.fdt = value;
    }

    /**
     * Gets the value of the idt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdt() {
        if (idt == null) {
            return "4s";
        } else {
            return idt;
        }
    }

    /**
     * Sets the value of the idt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdt(String value) {
        this.idt = value;
    }

    /**
     * Gets the value of the edt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdt() {
        if (edt == null) {
            return "4s";
        } else {
            return edt;
        }
    }

    /**
     * Sets the value of the edt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdt(String value) {
        this.edt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Dtmfexit {

        @XmlElementRefs({
            @XmlElementRef(name = "send", type = Send.class),
            @XmlElementRef(name = "exit", type = JAXBElement.class)
        })
        protected List<Object> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Exit" is used by two different parts of a schema. See: 
         * line 28 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * line 25 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link Send }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Noinput {

        @XmlElementRefs({
            @XmlElementRef(name = "send", type = Send.class),
            @XmlElementRef(name = "exit", type = JAXBElement.class)
        })
        protected List<Object> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Exit" is used by two different parts of a schema. See: 
         * line 28 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * line 25 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link Send }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Nomatch {

        @XmlElementRefs({
            @XmlElementRef(name = "send", type = Send.class),
            @XmlElementRef(name = "exit", type = JAXBElement.class)
        })
        protected List<Object> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Exit" is used by two different parts of a schema. See: 
         * line 28 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * line 25 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link Send }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *       &lt;attribute name="digits" use="required" type="{}basicDigits.datatype" />
     *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" fixed="moml+digits" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Pattern {

        @XmlElementRefs({
            @XmlElementRef(name = "send", type = Send.class),
            @XmlElementRef(name = "exit", type = JAXBElement.class)
        })
        protected List<Object> content;
        @XmlAttribute(required = true)
        protected String digits;
        @XmlAttribute
        protected String format;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Exit" is used by two different parts of a schema. See: 
         * line 28 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * line 25 of file:/F:/workspace/donkey/WebContent/msml/moml-core-module.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link Send }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

        /**
         * Gets the value of the digits property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDigits() {
            return digits;
        }

        /**
         * Sets the value of the digits property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDigits(String value) {
            this.digits = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            if (format == null) {
                return "moml+digits";
            } else {
                return format;
            }
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

    }

}
