//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 03:35:44 ���� CST 
//


package com.richitec.donkey.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{}msmlRequest" maxOccurs="unbounded"/>
 *         &lt;element name="event">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;sequence>
 *                     &lt;element name="name" type="{}msmlEventNameValue.datatype"/>
 *                     &lt;element name="value">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;pattern value="[a-zA-Z0-9.]+"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *                 &lt;attribute name="name" use="required" type="{}msmlEventName.datatype" />
 *                 &lt;attribute name="id" use="required" type="{}msmlEventSource.datatype" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z0-9.-_]+"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="confid" type="{}confID.datatype"/>
 *                     &lt;element name="dialogid" type="{}dialogID.datatype"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="response">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="\d{3}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="mark" type="{}mark.datatype" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msmlRequest",
    "event",
    "result"
})
@XmlRootElement(name = "msml")
public class Msml {

    @XmlElements({
        @XmlElement(name = "unjoin", type = Msml.Unjoin.class),
        @XmlElement(name = "destroyconference", type = Msml.Destroyconference.class),
        @XmlElement(name = "modifyconference", type = Msml.Modifyconference.class),
        @XmlElement(name = "join", type = Msml.Join.class),
        @XmlElement(name = "modifystream", type = Msml.Modifystream.class),
        @XmlElement(name = "dialogend", type = Msml.Dialogend.class),
        @XmlElement(name = "createconference", type = Msml.Createconference.class),
        @XmlElement(name = "reset", type = Msml.Reset.class),
        @XmlElement(name = "dialogstart", type = Msml.Dialogstart.class)
    })
    protected List<Object> msmlRequest;
    protected Msml.Event event;
    protected Msml.Result result;
    @XmlAttribute(required = true)
    protected String version = "1.1";

    /**
     * Gets the value of the msmlRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msmlRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsmlRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Msml.Unjoin }
     * {@link Msml.Destroyconference }
     * {@link Msml.Modifyconference }
     * {@link Msml.Join }
     * {@link Msml.Modifystream }
     * {@link Msml.Dialogend }
     * {@link Msml.Createconference }
     * {@link Msml.Reset }
     * {@link Msml.Dialogstart }
     * 
     * 
     */
    public List<Object> getMsmlRequest() {
        if (msmlRequest == null) {
            msmlRequest = new ArrayList<Object>();
        }
        return this.msmlRequest;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Msml.Event }
     *     
     */
    public Msml.Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msml.Event }
     *     
     */
    public void setEvent(Msml.Event value) {
        this.event = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Msml.Result }
     *     
     */
    public Msml.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msml.Result }
     *     
     */
    public void setResult(Msml.Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}audiomixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}videolayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute name="deletewhen" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="nomedia"/>
     *             &lt;enumeration value="nocontrol"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="term" type="{}boolean.datatype" default="true" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Createconference {

        protected AudiomixType audiomix;
        protected VideolayoutType videolayout;
        @XmlAttribute
        protected String name;
        @XmlAttribute(required = true)
        protected String deletewhen;
        @XmlAttribute
        protected BooleanDatatype term;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link AudiomixType }
         *     
         */
        public AudiomixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link AudiomixType }
         *     
         */
        public void setAudiomix(AudiomixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link VideolayoutType }
         *     
         */
        public VideolayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link VideolayoutType }
         *     
         */
        public void setVideolayout(VideolayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the deletewhen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeletewhen() {
            return deletewhen;
        }

        /**
         * Sets the value of the deletewhen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeletewhen(String value) {
            this.deletewhen = value;
        }

        /**
         * Gets the value of the term property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getTerm() {
            if (term == null) {
                return BooleanDatatype.TRUE;
            } else {
                return term;
            }
        }

        /**
         * Sets the value of the term property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setTerm(BooleanDatatype value) {
            this.term = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}basicAudioMixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}basicVideoLayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="id" use="required" type="{}confID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Destroyconference {

        protected BasicAudioMixType audiomix;
        protected BasicVideoLayoutType videolayout;
        @XmlAttribute(required = true)
        protected String id;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link BasicAudioMixType }
         *     
         */
        public BasicAudioMixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicAudioMixType }
         *     
         */
        public void setAudiomix(BasicAudioMixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link BasicVideoLayoutType }
         *     
         */
        public BasicVideoLayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicVideoLayoutType }
         *     
         */
        public void setVideolayout(BasicVideoLayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" use="required" type="{}dialogID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Dialogend {

        @XmlAttribute(required = true)
        protected String id;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;group ref="{}momlRequest"/>
     *         &lt;element name="group">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}play"/>
     *                   &lt;element ref="{}dtmf"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *       &lt;attribute name="target" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="type" use="required" type="{}dialogLanguage.datatype" fixed="application/moml+xml" />
     *       &lt;attribute name="name" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"group",
        "primitive",
        "control",
        "send"
    })
    public static class Dialogstart {

    	protected Msml.Dialogstart.Group group;
        @XmlElementRef(name = "primitive", type = JAXBElement.class)
        protected JAXBElement<? extends PrimitiveType> primitive;
        protected ControlType control;
        protected List<Send> send;
        @XmlAttribute(required = true)
        protected String target;
        @XmlAttribute(required = true)
        protected DialogLanguageDatatype type;
        @XmlAttribute
        protected String name;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the primitive property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link Dtmf }{@code >}
         *     {@link JAXBElement }{@code <}{@link Play }{@code >}
         *     {@link JAXBElement }{@code <}{@link Dtmfgen }{@code >}
         *     {@link JAXBElement }{@code <}{@link PrimitiveType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Record }{@code >}
         *     
         */
        public JAXBElement<? extends PrimitiveType> getPrimitive() {
            return primitive;
        }

        /**
         * Sets the value of the primitive property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link Dtmf }{@code >}
         *     {@link JAXBElement }{@code <}{@link Play }{@code >}
         *     {@link JAXBElement }{@code <}{@link Dtmfgen }{@code >}
         *     {@link JAXBElement }{@code <}{@link PrimitiveType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Record }{@code >}
         *     
         */
        public void setPrimitive(JAXBElement<? extends PrimitiveType> value) {
            this.primitive = ((JAXBElement<? extends PrimitiveType> ) value);
        }

        /**
         * Gets the value of the control property.
         * 
         * @return
         *     possible object is
         *     {@link ControlType }
         *     
         */
        public ControlType getControl() {
            return control;
        }

        /**
         * Sets the value of the control property.
         * 
         * @param value
         *     allowed object is
         *     {@link ControlType }
         *     
         */
        public void setControl(ControlType value) {
            this.control = value;
        }

        /**
         * Gets the value of the send property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the send property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSend().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Send }
         * 
         * 
         */
        public List<Send> getSend() {
            if (send == null) {
                send = new ArrayList<Send>();
            }
            return this.send;
        }

        /**
         * Gets the value of the group property.
         * 
         * @return
         *     possible object is
         *     {@link Msml.Dialogstart.Group }
         *     
         */
        public Msml.Dialogstart.Group getGroup() {
            return group;
        }

        /**
         * Sets the value of the group property.
         * 
         * @param value
         *     allowed object is
         *     {@link Msml.Dialogstart.Group }
         *     
         */
        public void setGroup(Msml.Dialogstart.Group value) {
            this.group = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link DialogLanguageDatatype }
         *     
         */
        public DialogLanguageDatatype getType() {
            if (type == null) {
                return DialogLanguageDatatype.APPLICATION_MOML_XML;
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link DialogLanguageDatatype }
         *     
         */
        public void setType(DialogLanguageDatatype value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}play"/>
         *         &lt;element ref="{}dtmf"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "play",
            "dtmf"
        })
        public static class Group {

            @XmlElement
            protected Play play;
            @XmlElement
            protected Dtmf dtmf;
            @XmlAttribute
            protected String topology;

            /**
             * Gets the value of the play property.
             * 
             * @return
             *     possible object is
             *     {@link Play }
             *     
             */
            public Play getPlay() {
                return play;
            }

            /**
             * Sets the value of the play property.
             * 
             * @param value
             *     allowed object is
             *     {@link Play }
             *     
             */
            public void setPlay(Play value) {
                this.play = value;
            }

            /**
             * Gets the value of the dtmf property.
             * 
             * @return
             *     possible object is
             *     {@link Dtmf }
             *     
             */
            public Dtmf getDtmf() {
                return dtmf;
            }

            /**
             * Sets the value of the dtmf property.
             * 
             * @param value
             *     allowed object is
             *     {@link Dtmf }
             *     
             */
            public void setDtmf(Dtmf value) {
                this.dtmf = value;
            }
            
            public void setTopology(){
            	this.topology = "parallel";
            }
            
            public String getTopology(){
            	return this.topology;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;sequence>
     *           &lt;element name="name" type="{}msmlEventNameValue.datatype"/>
     *           &lt;element name="value">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;pattern value="[a-zA-Z0-9.]+"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *       &lt;attribute name="name" use="required" type="{}msmlEventName.datatype" />
     *       &lt;attribute name="id" use="required" type="{}msmlEventSource.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameAndValue"
    })
    public static class Event {

        @XmlElementRefs({
            @XmlElementRef(name = "value", type = JAXBElement.class),
            @XmlElementRef(name = "name", type = JAXBElement.class)
        })
        protected List<JAXBElement<String>> nameAndValue;
        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute(required = true)
        protected String id;

        /**
         * Gets the value of the nameAndValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nameAndValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNameAndValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getNameAndValue() {
            if (nameAndValue == null) {
                nameAndValue = new ArrayList<JAXBElement<String>>();
            }
            return this.nameAndValue;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}streamType" maxOccurs="4" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Join {

        protected List<StreamType> stream;
        @XmlAttribute(required = true)
        protected String id1;
        @XmlAttribute(required = true)
        protected String id2;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StreamType }
         * 
         * 
         */
        public List<StreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<StreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}audiomixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}videolayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="id" use="required" type="{}confID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Modifyconference {

        protected AudiomixType audiomix;
        protected VideolayoutType videolayout;
        @XmlAttribute(required = true)
        protected String id;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link AudiomixType }
         *     
         */
        public AudiomixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link AudiomixType }
         *     
         */
        public void setAudiomix(AudiomixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link VideolayoutType }
         *     
         */
        public VideolayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link VideolayoutType }
         *     
         */
        public void setVideolayout(VideolayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}streamType" maxOccurs="4" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="mark" type="{}mark.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Modifystream {

        protected List<StreamType> stream;
        @XmlAttribute(required = true)
        protected String id1;
        @XmlAttribute(required = true)
        protected String id2;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StreamType }
         * 
         * 
         */
        public List<StreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<StreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="context" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="all"/>
     *             &lt;enumeration value="annc"/>
     *             &lt;enumeration value="conf"/>
     *             &lt;enumeration value="dialog"/>
     *             &lt;enumeration value="msml"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="mark" type="{}mark.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Reset {

        @XmlAttribute(required = true)
        protected String context;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContext(String value) {
            this.context = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[a-zA-Z0-9.-_]+"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="confid" type="{}confID.datatype"/>
     *           &lt;element name="dialogid" type="{}dialogID.datatype"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="response">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="\d{3}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="mark" type="{}mark.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "confidOrDialogid"
    })
    public static class Result {

        protected String description;
        @XmlElementRefs({
            @XmlElementRef(name = "confid", type = JAXBElement.class),
            @XmlElementRef(name = "dialogid", type = JAXBElement.class)
        })
        protected List<JAXBElement<String>> confidOrDialogid;
        @XmlAttribute
        protected String response;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the confidOrDialogid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the confidOrDialogid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConfidOrDialogid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getConfidOrDialogid() {
            if (confidOrDialogid == null) {
                confidOrDialogid = new ArrayList<JAXBElement<String>>();
            }
            return this.confidOrDialogid;
        }

        /**
         * Gets the value of the response property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponse() {
            return response;
        }

        /**
         * Sets the value of the response property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponse(String value) {
            this.response = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}basicStreamType" maxOccurs="4" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Unjoin {

        protected List<BasicStreamType> stream;
        @XmlAttribute(required = true)
        protected String id1;
        @XmlAttribute(required = true)
        protected String id2;
        @XmlAttribute
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BasicStreamType }
         * 
         * 
         */
        public List<BasicStreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<BasicStreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }

}
