//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.29 at 03:35:44 ���� CST 
//


package com.richitec.donkey.msml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for videolayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="videolayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{}basicVideoLayoutType">
 *       &lt;choice>
 *         &lt;element name="selector">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}selectorType">
 *                 &lt;sequence>
 *                   &lt;element name="root" type="{}rootType"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "videolayoutType", propOrder = {
    "selector"
})
public class VideolayoutType
    extends BasicVideoLayoutType
{

    protected VideolayoutType.Selector selector;

    /**
     * Gets the value of the selector property.
     * 
     * @return
     *     possible object is
     *     {@link VideolayoutType.Selector }
     *     
     */
    public VideolayoutType.Selector getSelector() {
        return selector;
    }

    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideolayoutType.Selector }
     *     
     */
    public void setSelector(VideolayoutType.Selector value) {
        this.selector = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}selectorType">
     *       &lt;sequence>
     *         &lt;element name="root" type="{}rootType"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "root"
    })
    public static class Selector
        extends SelectorType
    {

        @XmlElement(required = true)
        protected RootType root;

        /**
         * Gets the value of the root property.
         * 
         * @return
         *     possible object is
         *     {@link RootType }
         *     
         */
        public RootType getRoot() {
            return root;
        }

        /**
         * Sets the value of the root property.
         * 
         * @param value
         *     allowed object is
         *     {@link RootType }
         *     
         */
        public void setRoot(RootType value) {
            this.root = value;
        }

    }

}
